version: '3.8'

services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    env_file:
      - .env.production
    ports:
      - "3000:3000"
    depends_on:
      - chopsticks

  app-test:
    build:
      context: .
      dockerfile: Dockerfile
    env_file:
      - .env.test
    command: ["yarn", "test"]
    depends_on:
      - chopsticks
    environment:
      NODE_ENV: test

  chopsticks:
    build:
      context: ./chopsticks
    volumes:
      - ./chopsticks/chopsticks.yml:/app/config/chopsticks.yml
    ports:
      - "8000:8000"
    command: ["npx", "@acala-network/chopsticks@latest", "-c", "/app/config/chopsticks.yml"]
