version: '3.8'

services:
  app-test:
    build:
      context: .
      dockerfile: Dockerfile
    env_file:
      - .env.test
    ports:
      - "16726:16726"
    command: ["yarn", "test"]
    depends_on:
      chopsticks:
        condition: service_healthy
    environment:
      NODE_ENV: test

  chopsticks:
    build:
      context: ./chopsticks
    volumes:
      - ./chopsticks/chopsticks.yml:/app/config/chopsticks.yml
    ports:
      - "8000:8000"
    command: ["chopsticks", "-c", "/app/config/chopsticks.yml"]
    healthcheck:
      test: ["CMD-SHELL", "curl -s -H 'Content-Type: application/json' -d '{\"id\":1, \"jsonrpc\":\"2.0\", \"method\": \"system_health\", \"params\":[]}' http://localhost:8000"]
      interval: 10s
      timeout: 5s
      retries: 10
